/**
 * Created by Mihail on 1/7/2017.
 */
export const SELECTED_IMAGE = 'SELECTED_IMAGE'
export const FLICKR_IMAGES_SUCCESS = 'FLICKR_IMAGES_SUCCESS'
export const SELECTED_VIDEO = 'SELECTED_VIDEO'
export const FLICKR_VIDEOS_SUCCESS = 'FLICKR_VIDEOS_SUCCESS'
export const SEARCH_IMAGES_REQUEST = 'SEARCH_IMAGES_REQUEST'
export const SEARCH_VIDEOS_REQUEST = 'SEARCH_VIDEOS_REQUEST'
export const SEARCH_IMAGES_ERROR = 'SEARCH_IMAGES_ERROR'
export const SEARCH_VIDEOS_ERROR = 'SEARCH_VIDEOS_ERROR'
export const PAGES_COUNT = 'PAGES_COUNT'