/**
 * Created by Mihail on 1/7/2017.
 */
export const SELECTED_IMAGE = 'SELECTED_IMAGE'
export const FLICKR_IMAGES_SUCCESS = 'FLICKR_IMAGES_SUCCESS'
export const SELECTED_VIDEO = 'SELECTED_VIDEO'
export const FLICKR_VIDEOS_SUCCESS = 'FLICKR_VIDEOS_SUCCESS'
export const SEARCH_MEDIA_REQUEST = 'SEARCH_MEDIA_REQUEST'
export const SEARCH_MEDIA_ERROR = 'SEARCH_MEDIA_ERROR'